### ISSUE TITLE
Question for some nps candidate has negative index. why?

### ISSUE THREAD

**Issue by becxer** [bdhingra/quasar#1]
I saw several candidates in {}_nps.json has negative index like  ['4', -1, -2].
What are these meaning?

**Comment by bdhingra** [comment]
When the correct answer to the question is not detected as an NP chunk, we add it to the list of candidates. _Both_ the context_id and token_id for these are set to negative integers.

However, I realize due to a small bug there were other numeric chunks creeping in the list of candidates as well. In these cases _only_ the token_id is set to a negative value.

So you can throw out the candidates where the context_id is positive but token_id is negative. Candidates where both of these are negative are the correct answer.

I'm going to put out a new release where there are no false candidates and update the readme as well. Thanks for pointing this out!

**Comment by becxer** [comment]
Oh, Thank you for detail explain. You mean if correct answer is not found in passage then set it's context index to negative. Is it python way indexing (for example, in python -1 meaning last cell)? or just put negative sign to number?

**Comment by bdhingra** [comment]
We just put a negative number to indicate that it does not match to any context. Now that you say it, I agree that this is not the ideal way of indicating that. I'll fix that if we make another release, but for now I have just added this information to the readme.
